In [1]:
#!pip install plotly
#!pip install cufflinks

In [2]:
import pandas as pd
import numpy as np

import plotly.offline as pl
pl.init_notebook_mode(connected=True)
from plotly.graph_objs import Scatter, Layout, Histogram, Contours, Marker

from sklearn.metrics import precision_recall_fscore_support, precision_recall_curve, confusion_matrix

In [3]:
pl.iplot({
    "data": [Scatter(x=[1, 2, 3, 4], y=[4, 3, 2, 1])],
    "layout": Layout(title="hello world")
})

In [4]:
from plotly.graph_objs import *
import numpy as np

x = np.random.randn(2000)
y = np.random.randn(2000)
pl.iplot([Histogram2dContour(x=x, y=y, contours=Contours(coloring='heatmap')),
       Scatter(x=x, y=y, mode='markers', marker=Marker(color='white', size=3, opacity=0.3))], show_link=False)

# Precision, recall, f1 and support from sklearn

* **precision:** 
    * out of all examples classified as positive, how many truly were? <br>
    * **minimize false positives** <br>
    * certain that what you classified as positive, really is <br>
    * $\frac{tp}{tp+fp}$
    * spam detection
<br>
<br>
* **recall:** 
    * out of all true examples of the class, how many were classified as being so? <br>
    * **minimize false negatives** <br>
    * certain that you got all/most of positive cases <br>
    * $\frac{tp}{tp+fn}$
    * cancer detection, fraud detection

In [8]:
yt = np.array(['cat', 'dog', 'pig', 'cat', 'dog', 'pig'])
yp = np.array(['cat', 'pig', 'dog', 'cat', 'cat', 'dog'])

In [9]:
precision_recall_fscore_support(yt, yp)

(array([ 0.66666667,  0.        ,  0.        ]),
 array([ 1.,  0.,  0.]),
 array([ 0.8,  0. ,  0. ]),
 array([2, 2, 2], dtype=int64))

In [10]:
precision_recall_fscore_support(yt, yp, average='weighted')

(0.22222222222222221, 0.33333333333333331, 0.26666666666666666, None)

In [18]:
yt = np.array([1, 0, 1, 0, 1, 0, 1, 0])
yp = np.array([1, 1, 1, 1, 1, 1, 0, 0])

In [19]:
precision_recall_fscore_support(yt, yp)

(array([ 0.5,  0.5]),
 array([ 0.25,  0.75]),
 array([ 0.33333333,  0.6       ]),
 array([4, 4], dtype=int64))

In [21]:
precision_recall_fscore_support(yt, yp, average='weighted')

(0.5, 0.5, 0.46666666666666667, None)

In [22]:
precision_recall_fscore_support(yt, yp, average='binary')

(0.5, 0.75, 0.59999999999999998, None)

In [25]:
confusion_matrix(yt, yp)

array([[1, 3],
       [1, 3]], dtype=int64)

### Confusion matrix multiclass
* rows = ytrue
* cols = ypred

In [4]:
y_true = ["cat", "ant", "cat", "cat", "ant", "bird"]
y_pred = ["ant", "ant", "cat", "cat", "ant", "cat"]
confusion_matrix(y_true, y_pred, labels=["ant", "bird", "cat"])


array([[2, 0, 0],
       [0, 0, 1],
       [1, 0, 2]], dtype=int64)

In [5]:
confusion_matrix(y_true, y_pred, labels=["ant", "cat", "bird"])

array([[2, 0, 0],
       [1, 2, 0],
       [0, 1, 0]], dtype=int64)